# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'Futility iOS' do
    pod 'Mixpanel'
end

target 'Futility Android' do

end

target 'Futility Mac' do

end

